import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#030000] text-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen overflow-hidden`}
      >
        {/* Neon Red Sidebar */}
        <aside className="w-64 bg-[#050000] border-r border-[#1a0000] flex flex-col justify-between relative">
          {/* Animated Neon Border on the right edge */}
          <div className="absolute right-0 top-0 w-[1px] h-full border-neon-flow opacity-50"></div>
          
          <div className="p-6">
            <h1 className="text-2xl font-black tracking-tighter flex items-center gap-2 mb-10">
              <span className="text-neon-flow font-bold text-3xl">K</span> 
              <span className="text-zinc-300">SAFE</span>
            </h1>

            <nav className="space-y-4">
              <a href="#" className="flex items-center gap-3 text-red-500 bg-red-950/20 px-4 py-3 rounded-lg border border-red-900/30 transition-all hover:shadow-[0_0_15px_rgba(255,0,60,0.2)]">
                <span className="text-xl">⛨</span> Dashboard
              </a>
              <a href="#" className="flex items-center gap-3 text-zinc-500 hover:text-red-400 px-4 py-3 rounded-lg transition-all">
                <span className="text-xl">👥</span> Usuários
              </a>
              <a href="#" className="flex items-center gap-3 text-zinc-500 hover:text-red-400 px-4 py-3 rounded-lg transition-all">
                <span className="text-xl">📧</span> E-mails
              </a>
              <a href="#" className="flex items-center gap-3 text-zinc-500 hover:text-red-400 px-4 py-3 rounded-lg transition-all">
                <span className="text-xl">⚙️</span> Configurações
              </a>
            </nav>
          </div>

          <div className="p-6 border-t border-[#1a0000]">
            <button className="flex items-center gap-3 text-zinc-500 hover:text-red-500 w-full px-4 py-3 rounded-lg transition-all">
              <span className="text-xl">🚪</span> Sair
            </button>
          </div>
        </aside>

        {/* Main Content Area */}
        <main className="flex-1 overflow-y-auto relative">
          {/* Top Neon Ambient Glow */}
          <div className="absolute top-0 left-0 w-full h-32 bg-gradient-to-b from-red-900/10 to-transparent pointer-events-none"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
